package test;

import static aritmetica.Aritmetica.division;
import excepciones.OperacionExcepcion;

public class TestExcepciones {
    public static void main(String[] args) {
        int resultado = 0;
        try{
            resultado = division(10, 0);
            System.out.println("resultado = " + resultado);
        } catch(OperacionExcepcion e){
            System.out.println("Ocurri贸 un error de tipo OperacionExcepcion");
            System.out.println(e.getMessage());
        } catch(Exception e){
            System.out.println("Ocurri贸 un error");
            e.printStackTrace(System.out); // Se conoce como pila de excepciones
            System.out.println(e.getMessage());
        }
        finally{
            System.out.println("Se revis贸 la divisi贸n entre cero");
        }
        System.out.println("La variable resultado tiene valor "+resultado);
    }
}
